'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50215.44
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

<Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="My.Resources.Resources.get_ResourceManager():System.Resources.ResourceManager"),  _
 Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="My.Resources.Resources.get_Culture():System.Globalization.CultureInfo"),  _
 Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="My.Resources.Resources.set_Culture(System.Globalization.CultureInfo):Void")> 

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleName()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If (resourceMan Is Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cheater_2005.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _Mod() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Mod", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cheater() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("cheater", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cheater_2005_Logo() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Cheater 2005 Logo", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__10_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (10)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__106_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (106)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__113_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (113)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__140_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (140)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__152_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (152)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__153_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (153)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__158_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (158)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__167_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (167)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__176_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (176)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__239_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (239)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__240_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (240)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__3_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (3)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__43_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (43)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__47_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (47)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__54_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (54)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__84_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (84)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icons_16_8__89_() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Icons 16-8 (89)", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kalender_32x32_XP() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Kalender 32x32 XP", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mod1() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Mod1", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mod2() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Mod2", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Modschmal() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Modschmal", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property x() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("x", resourceCulture),System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
